import imagePath from "@/app/_assets/imagePath";

export const technologies = [
  { tech: "Java", image: imagePath.java },
  { tech: "JavaScript", image: imagePath.javaScript },
  { tech: "TypeScript", image: imagePath.typescript },
  { tech: "C++", image: imagePath.cpp },
  { tech: "C#", image: imagePath.csharp },
  { tech: "Ruby", image: imagePath.ruby },
  { tech: "Terraform", image: imagePath.terraform },
  { tech: "HTML", image: imagePath.html },
  { tech: "React", image: imagePath.react },
  { tech: "React Native", image: imagePath.reactNative },
  { tech: "Ruby on Rails", image: imagePath.rails },
  { tech: "Vite", image: imagePath.vite },
  { tech: "Bun", image: imagePath.bun },
  { tech: "Node.js", image: imagePath.node },
  { tech: "Express", image: imagePath.express },
  { tech: "Next.js", image: imagePath.next },
  { tech: "ThreeJS", image: imagePath.threejs },
  { tech: "jQuery", image: imagePath.jquery },
  { tech: "Microsoft Azure", image: imagePath.azure },
  { tech: "Amazon Web Services", image: imagePath.aws },
  { tech: "PostgreSQL", image: imagePath.postgreSQL },
  { tech: "MySQL", image: imagePath.mySQL },
  { tech: "SQLite", image: imagePath.sqlite },
  { tech: "MongoDB", image: imagePath.mongodb },
  { tech: "Firebase", image: imagePath.firebase },
  { tech: "Neo4j", image: imagePath.neo4j },
  { tech: "Vector DBs", image: imagePath.vectordb },
  { tech: "LangChain/LangGraph", image: imagePath.langchain },
  { tech: "RESTful APIs", image: imagePath.api },
  { tech: "CSS", image: imagePath.css },
  { tech: "SCSS", image: imagePath.scss },
  { tech: "Tailwind CSS", image: imagePath.tailwind },
  { tech: "Bootstrap", image: imagePath.bootstrap },
  { tech: "Linux", image: imagePath.linux },
  { tech: "Git", image: imagePath.git },
  { tech: "VS Code", image: imagePath.vscode },
];
