import imagePath from "@/app/_assets/imagePath";

export const technologies = [
  { tech: "Java", image: imagePath.java },
  { tech: "C++", image: imagePath.cpp },
  { tech: "Ruby", image: imagePath.ruby },
  { tech: "Ruby on Rails", image: imagePath.rails },
  { tech: "HTML", image: imagePath.html },
  { tech: "CSS", image: imagePath.css },
  { tech: "SCSS", image: imagePath.scss },
  { tech: "Tailwind CSS", image: imagePath.tailwind },
  { tech: "Bootstrap", image: imagePath.bootstrap },
  { tech: "JavaScript", image: imagePath.javaScript },
  { tech: "React", image: imagePath.react },
  { tech: "React Native", image: imagePath.reactNative },
  { tech: "Next.js", image: imagePath.next },
  { tech: "Vite", image: imagePath.vite },
  { tech: "ThreeJS", image: imagePath.threejs },
  { tech: "jQuery", image: imagePath.jquery },
  { tech: "Node.js", image: imagePath.node },
  { tech: "Bun", image: imagePath.bun },
  { tech: "Express", image: imagePath.express },
  { tech: "PostgreSQL", image: imagePath.postgreSQL },
  { tech: "MySQL", image: imagePath.mySQL },
  { tech: "SQLite", image: imagePath.sqlite },
  { tech: "Firebase", image: imagePath.firebase },
  { tech: "RESTful APIs", image: imagePath.api },
  { tech: "Git", image: imagePath.git },
  { tech: "VS Code", image: imagePath.vscode },
  { tech: "Linux", image: imagePath.linux },
];
